---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: documents
- type: directory
  path: _my_tags
  label: My tags
  create: all
  match: "**/*"
upload_dir: files
public_path: http://jacksonmooring.com/.netlify/large-media
front_matter_path: ''
use_front_matter_path: 
file_template: ":month:-:day:-:year:--file-mm-dd-yy--:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install; sh ./bin/setup
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
